include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - prefer_final_in_for_each
    - prefer_final_locals
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - use_string_buffers
    - public_member_api_docs
    
analyzer:
  exclude:
    - tool/*
    - example/*
  errors:
    lines_longer_than_80_chars: ignore
    avoid_print: error